<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MPengajuan_pengadaan extends CI_Model
{

    public $table = 'pengajuan_pengadaan';
    public $id = 'id_pengajuan_pengadaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pengajuan_pengadaan', $q);
	$this->db->or_like('id_stok_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('tanggal_pengajuan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {

          //join tabel 
    $this->db->select('pp.*,sb.kode_barang,sb.nama_barang');
    $this->db->from('pengajuan_pengadaan pp');
    $this->db->join('stok_barang sb', 'sb.id_stok_barang = pp.id_stok_barang');
   
        $this->db->order_by('pp.id_pengajuan_pengadaan', $this->order);
        $this->db->like('pp.id_pengajuan_pengadaan', $q);
	$this->db->or_like('pp.id_stok_barang', $q);
	$this->db->or_like('pp.nama_barang', $q);
	$this->db->or_like('pp.tanggal_pengajuan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MPengajuan_pengadaan.php */
/* Location: ./application/models/MPengajuan_pengadaan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-27 06:43:08 */
/* http://harviacode.com */